(defconstant big 224403121196654400)
(defun nearly-square-divs (n)
  (let* ((s (round (sqrt n)))
         (r (/ (rem n s) 2))
         (upper (+ s r))
         (lower (- s r)))
    (format t "~a ~a ~a ~a~%" s r upper lower)
    (cond ((zerop (rem n upper)) (list upper (/ n upper)))
          ((zerop (rem n lower)) (list lower (/ n lower)))
          (t "? ?"))))

(nearly-square-divs (/ big 64))
(do ((n big (/ n 2)) lst) ((plusp (rem n 2)) lst)
  (push 2 lst))
